version: "3.7"
services:
  zookeeper1:
    entrypoint: /bin/bash run-zookeeper.sh --myid 1
    image: "docker.io/dockeralexandrtalan/zookeeper"
    volumes:
      - ./zookeeper-config:/usr/local/lib/apache-zookeeper-3.5.6-bin/conf
    ports:
      - "2181:2181"
    networks:
      - zookeeper
  zookeeper2:
    entrypoint: /bin/bash run-zookeeper.sh --myid 2
    image: "docker.io/dockeralexandrtalan/zookeeper"
    volumes:
      - ./zookeeper-config:/usr/local/lib/apache-zookeeper-3.5.6-bin/conf
    ports:
      - "2182:2181"
    networks:
      - zookeeper
  zookeeper3:
    entrypoint: /bin/bash run-zookeeper.sh --myid 3
    image: "docker.io/dockeralexandrtalan/zookeeper"
    volumes:
      - ./zookeeper-config:/usr/local/lib/apache-zookeeper-3.5.6-bin/conf
    ports:
      - "2183:2181"
    networks:
      - zookeeper
networks:
  zookeeper: